### ISSUE TITLE
Issue reading psf file generated with ParmEd

### ISSUE THREAD

**Issue by maurobedoya** [franciscoadasme/chem.cr#190]
Reading a topology file (PSF) generated with ParmEd for a ligand using the AMBER ff, I found the following error:

```
Found a parsing issue in xx.psf:
 7 |          1 SYS      1        N4I      C        C3LTU    0.055500       12.0100
                                                                       ^^^^
Error: Invalid real number
Unhandled exception: Invalid real number (Chem::ParseException)
```

This is due to the format verification in the [psf.cr](https://github.com/franciscoadasme/chem.cr/blob/b94bde4f584ed2732ccf8931fa6366c10c698640/src/chem/formats/psf.cr) module.

The ParmEd format contains in the header the following elements:
`PSF CHEQ EXT XPLOR`

Therefore, the choosen format is `EXT`, however it does not match the `EXT` format, insted it works with the else condition on line [45](https://github.com/franciscoadasme/chem.cr/blob/b94bde4f584ed2732ccf8931fa6366c10c698640/src/chem/formats/psf.cr#L45) of the  [psf.cr](https://github.com/franciscoadasme/chem.cr/blob/b94bde4f584ed2732ccf8931fa6366c10c698640/src/chem/formats/psf.cr) module.

A workaround is to change the line [22](https://github.com/franciscoadasme/chem.cr/blob/b94bde4f584ed2732ccf8931fa6366c10c698640/src/chem/formats/psf.cr#L22) by:
```crystal
format = {"NAMD", "CHEQ", "EXT"}.find(&.in?(flags)) || "STANDARD"
```
It is not a good fix, but `CHEQ` will raise the `True` condition first and therefore the format won´t be `EXT` or `STANDARD`.

Here is attached the psf file.
[N4I.txt](https://github.com/franciscoadasme/chem.cr/files/9747752/N4I.txt)

**Comment by franciscoadasme** [comment]
Fix in 2b0f42abef2d37bfd2a28a0b6606ee3936ffd943
